import { computePriorityScore } from "./scoring";
import type {
  Requirement,
  SurplusItem,
  Transaction,
  User,
} from "./types";

const hoursAgo = (h: number) =>
  new Date(Date.now() - h * 3600_000).toISOString();

function req(
  partial: Omit<
    Requirement,
    "priority" | "priorityScore" | "scoreBreakdown" | "status"
  > & { quantityFulfilled: number },
): Requirement {
  const scored = computePriorityScore({
    peopleAffected: partial.peopleAffected,
    quantityRequired: partial.quantityNeeded,
    quantityFulfilled: partial.quantityFulfilled,
    durationDays: partial.durationDays,
    urgency: partial.urgency,
  });
  const remaining = partial.quantityNeeded - partial.quantityFulfilled;
  const status =
    remaining <= 0
      ? "fulfilled"
      : partial.quantityFulfilled > 0
        ? "partial"
        : "open";
  return {
    ...partial,
    status,
    priority: scored.priority,
    priorityScore: scored.score,
    scoreBreakdown: scored.breakdown,
  };
}

export const seedUsers: User[] = [
  {
    id: "u-ananya",
    name: "Ananya Rao",
    role: "donor",
    contributionType: "food",
    location: "Bengaluru",
  },
  {
    id: "u-priya",
    name: "Priya Shah",
    role: "donor",
    contributionType: "medical",
    location: "Hyderabad",
  },
  {
    id: "u-ravi",
    name: "Ravi Menon",
    role: "receiver",
    orgName: "Camp Sundari",
    location: "East Bank",
  },
  {
    id: "u-fatima",
    name: "Fatima Begum",
    role: "receiver",
    orgName: "Camp Lakshmi",
    location: "West Marsh",
  },
  {
    id: "u-dev",
    name: "Dev Patel",
    role: "receiver",
    orgName: "Camp Meera",
    location: "North Ridge",
  },
  {
    id: "u-nisha",
    name: "Nisha Verma",
    role: "receiver",
    orgName: "Camp Anjuman",
    location: "River Fork",
  },
  {
    id: "u-arjun",
    name: "Arjun Das",
    role: "receiver",
    orgName: "Camp Rohan",
    location: "South Fields",
  },
  {
    id: "u-sara",
    name: "Sara Joseph",
    role: "receiver",
    orgName: "Camp Noor",
    location: "Highway 9",
  },
  {
    id: "u-leila",
    name: "Leila Hassan",
    role: "coordinator",
    region: "Kaveri Basin",
    location: "Basin HQ",
  },
  {
    id: "u-omar",
    name: "Omar Khalid",
    role: "coordinator",
    region: "Highway Corridor",
    location: "Mile 14 Depot",
  },
];

export const seedRequirements: Requirement[] = [
  req({
    id: "req-lakshmi-water",
    title: "Drinking water for West Marsh",
    campName: "Camp Lakshmi",
    receiverId: "u-fatima",
    resourceType: "water",
    quantityNeeded: 1000,
    quantityUnit: "litres",
    quantityFulfilled: 0,
    peopleAffected: 2000,
    durationDays: 1,
    urgency: 5,
    location: "West Marsh",
    mapX: 18,
    mapY: 42,
    notes:
      "Embankment breach overnight. Hand pumps silted. Children under five: 310. Tanker access possible via the west levee road until 18:00.",
    createdAt: hoursAgo(4),
  }),
  req({
    id: "req-sundari-food",
    title: "Kitchen tents out of rations",
    campName: "Camp Sundari",
    receiverId: "u-ravi",
    resourceType: "food",
    quantityNeeded: 500,
    quantityUnit: "packets",
    quantityFulfilled: 120,
    peopleAffected: 1200,
    durationDays: 3,
    urgency: 5,
    location: "East Bank",
    mapX: 72,
    mapY: 38,
    notes:
      "One gas cylinder remaining. 180 children under five. Ready-to-eat packets preferred — no dry fuel on site.",
    createdAt: hoursAgo(9),
  }),
  req({
    id: "req-noor-hygiene",
    title: "Hygiene kits after overflow",
    campName: "Camp Noor",
    receiverId: "u-sara",
    resourceType: "hygiene",
    quantityNeeded: 80,
    quantityUnit: "kits",
    quantityFulfilled: 20,
    peopleAffected: 300,
    durationDays: 5,
    urgency: 4,
    location: "Highway 9",
    mapX: 82,
    mapY: 62,
    notes:
      "Latrine overflow after the second crest. Skin infections starting in the south row of tents.",
    createdAt: hoursAgo(14),
  }),
  req({
    id: "req-meera-clothing",
    title: "Blankets for North Ridge nights",
    campName: "Camp Meera",
    receiverId: "u-dev",
    resourceType: "clothing",
    quantityNeeded: 200,
    quantityUnit: "blankets",
    quantityFulfilled: 40,
    peopleAffected: 400,
    durationDays: 7,
    urgency: 4,
    location: "North Ridge",
    mapX: 48,
    mapY: 18,
    notes:
      "Elevation is dry but nights drop to 14°C. Elderly ward has no floor insulation.",
    createdAt: hoursAgo(20),
  }),
  req({
    id: "req-anjuman-medical",
    title: "Field clinic restock",
    campName: "Camp Anjuman",
    receiverId: "u-nisha",
    resourceType: "medical",
    quantityNeeded: 50,
    quantityUnit: "kits",
    quantityFulfilled: 10,
    peopleAffected: 80,
    durationDays: 2,
    urgency: 3,
    location: "River Fork",
    mapX: 40,
    mapY: 48,
    notes:
      "ORS, antiseptic, and tetanus dressings. Clinic tent is standing; only stock is short.",
    createdAt: hoursAgo(6),
  }),
  req({
    id: "req-rohan-shelter",
    title: "Family tents for South Fields",
    campName: "Camp Rohan",
    receiverId: "u-arjun",
    resourceType: "shelter",
    quantityNeeded: 30,
    quantityUnit: "tents",
    quantityFulfilled: 6,
    peopleAffected: 150,
    durationDays: 14,
    urgency: 2,
    location: "South Fields",
    mapX: 55,
    mapY: 78,
    notes:
      "Ground is draining. Families currently sharing tarps. Not an immediate medical risk.",
    createdAt: hoursAgo(30),
  }),
];

export const seedSurplus: SurplusItem[] = [
  {
    id: "sur-anjuman-blankets",
    campName: "Camp Anjuman",
    receiverId: "u-nisha",
    resourceType: "clothing",
    quantity: 80,
    quantityUnit: "blankets",
    location: "River Fork",
    mapX: 40,
    mapY: 48,
    notes: "Winter stock never issued. Dry, bagged, ready to load.",
    createdAt: hoursAgo(8),
    status: "available",
  },
  {
    id: "sur-rohan-food",
    campName: "Camp Rohan",
    receiverId: "u-arjun",
    resourceType: "food",
    quantity: 200,
    quantityUnit: "packets",
    location: "South Fields",
    mapX: 55,
    mapY: 78,
    notes: "Rice packets from a delayed convoy. We cannot store past Friday.",
    createdAt: hoursAgo(5),
    status: "available",
  },
  {
    id: "sur-meera-water",
    campName: "Camp Meera",
    receiverId: "u-dev",
    resourceType: "water",
    quantity: 400,
    quantityUnit: "litres",
    location: "North Ridge",
    mapX: 48,
    mapY: 18,
    notes: "Spring-fed tank at capacity. Jerrycans available for transfer.",
    createdAt: hoursAgo(11),
    status: "available",
  },
];

export const seedTransactions: Transaction[] = [
  {
    id: "tx-1001",
    kind: "donation",
    requirementId: "req-sundari-food",
    donorId: "u-ananya",
    donorName: "Ananya Rao",
    receiverId: "u-ravi",
    receiverName: "Ravi Menon",
    campName: "Camp Sundari",
    resourceType: "food",
    quantity: 120,
    quantityUnit: "packets",
    declaredAmount: 120,
    stage: "donated",
    stageHistory: [
      { stage: "pending", at: hoursAgo(8), by: "Ananya Rao" },
      { stage: "donated", at: hoursAgo(7.5), by: "Ananya Rao" },
    ],
    proofs: [
      {
        id: "pf-1001-a",
        uploadedBy: "donor",
        uploaderName: "Ananya Rao",
        kind: "receipt",
        fileName: "kirana-receipt.jpg",
        dataUrl: "",
        mimeType: "image/jpeg",
        amountEntered: 120,
        uploadedAt: hoursAgo(7.4),
        verification: "verified",
      },
    ],
    disputed: false,
    createdAt: hoursAgo(8),
    notes: "Packed at the east warehouse. Awaiting coordinator pickup.",
  },
  {
    id: "tx-1002",
    kind: "donation",
    requirementId: "req-anjuman-medical",
    donorId: "u-priya",
    donorName: "Priya Shah",
    coordinatorId: "u-leila",
    coordinatorName: "Leila Hassan",
    receiverId: "u-nisha",
    receiverName: "Nisha Verma",
    campName: "Camp Anjuman",
    resourceType: "medical",
    quantity: 10,
    quantityUnit: "kits",
    declaredAmount: 10,
    stage: "in_transit",
    stageHistory: [
      { stage: "pending", at: hoursAgo(16), by: "Priya Shah" },
      { stage: "donated", at: hoursAgo(15), by: "Priya Shah" },
      {
        stage: "received_by_coordinator",
        at: hoursAgo(12),
        by: "Leila Hassan",
      },
      { stage: "in_transit", at: hoursAgo(3), by: "Leila Hassan" },
    ],
    proofs: [
      {
        id: "pf-1002-a",
        uploadedBy: "donor",
        uploaderName: "Priya Shah",
        kind: "invoice",
        fileName: "clinic-invoice.pdf",
        dataUrl: "",
        mimeType: "application/pdf",
        amountEntered: 10,
        uploadedAt: hoursAgo(15),
        verification: "verified",
      },
      {
        id: "pf-1002-b",
        uploadedBy: "coordinator",
        uploaderName: "Leila Hassan",
        kind: "delivery_bill",
        fileName: "waybill-14.jpg",
        dataUrl: "",
        mimeType: "image/jpeg",
        amountEntered: 10,
        uploadedAt: hoursAgo(3),
        verification: "verified",
      },
    ],
    disputed: false,
    createdAt: hoursAgo(16),
    notes: "Boat crossing at River Fork — ETA before dusk.",
  },
  {
    id: "tx-1003",
    kind: "donation",
    requirementId: "req-noor-hygiene",
    donorId: "u-ananya",
    donorName: "Ananya Rao",
    coordinatorId: "u-omar",
    coordinatorName: "Omar Khalid",
    receiverId: "u-sara",
    receiverName: "Sara Joseph",
    campName: "Camp Noor",
    resourceType: "hygiene",
    quantity: 20,
    quantityUnit: "kits",
    declaredAmount: 20,
    stage: "delivered",
    stageHistory: [
      { stage: "pending", at: hoursAgo(40), by: "Ananya Rao" },
      { stage: "donated", at: hoursAgo(38), by: "Ananya Rao" },
      {
        stage: "received_by_coordinator",
        at: hoursAgo(30),
        by: "Omar Khalid",
      },
      { stage: "in_transit", at: hoursAgo(22), by: "Omar Khalid" },
      { stage: "delivered", at: hoursAgo(6), by: "Sara Joseph" },
    ],
    proofs: [
      {
        id: "pf-1003-a",
        uploadedBy: "donor",
        uploaderName: "Ananya Rao",
        kind: "receipt",
        fileName: "hygiene-challan.jpg",
        dataUrl: "",
        mimeType: "image/jpeg",
        amountEntered: 20,
        uploadedAt: hoursAgo(38),
        verification: "verified",
      },
      {
        id: "pf-1003-c",
        uploadedBy: "receiver",
        uploaderName: "Sara Joseph",
        kind: "delivery_bill",
        fileName: "gate-pass.jpg",
        dataUrl: "",
        mimeType: "image/jpeg",
        amountEntered: 20,
        uploadedAt: hoursAgo(6),
        verification: "verified",
      },
    ],
    disputed: false,
    createdAt: hoursAgo(40),
    notes: "Unloaded at Highway 9 gate. Awaiting distribution record.",
  },
  {
    id: "tx-1004",
    kind: "donation",
    requirementId: "req-lakshmi-water",
    donorId: "u-priya",
    donorName: "Priya Shah",
    coordinatorId: "u-leila",
    coordinatorName: "Leila Hassan",
    receiverId: "u-fatima",
    receiverName: "Fatima Begum",
    campName: "Camp Lakshmi",
    resourceType: "water",
    quantity: 200,
    quantityUnit: "litres",
    declaredAmount: 200,
    stage: "delivered",
    stageHistory: [
      { stage: "pending", at: hoursAgo(18), by: "Priya Shah" },
      { stage: "donated", at: hoursAgo(17), by: "Priya Shah" },
      {
        stage: "received_by_coordinator",
        at: hoursAgo(14),
        by: "Leila Hassan",
      },
      { stage: "in_transit", at: hoursAgo(10), by: "Leila Hassan" },
      { stage: "delivered", at: hoursAgo(2), by: "Fatima Begum" },
    ],
    proofs: [
      {
        id: "pf-1004-a",
        uploadedBy: "donor",
        uploaderName: "Priya Shah",
        kind: "invoice",
        fileName: "tanker-invoice.pdf",
        dataUrl: "",
        mimeType: "application/pdf",
        amountEntered: 200,
        uploadedAt: hoursAgo(17),
        verification: "verified",
      },
      {
        id: "pf-1004-b",
        uploadedBy: "receiver",
        uploaderName: "Fatima Begum",
        kind: "delivery_bill",
        fileName: "dipstick-log.jpg",
        dataUrl: "",
        mimeType: "image/jpeg",
        amountEntered: 140,
        uploadedAt: hoursAgo(2),
        verification: "mismatch_flagged",
      },
    ],
    disputed: true,
    disputeReason:
      "Declared 200 litres. Receiver dipstick log records 140 litres. Auto-flagged for coordinator review.",
    createdAt: hoursAgo(18),
    notes: "Tanker arrived short. Dipstick reading does not match invoice.",
  },
  {
    id: "tx-1005",
    kind: "donation",
    requirementId: "req-meera-clothing",
    donorId: "u-ananya",
    donorName: "Ananya Rao",
    coordinatorId: "u-leila",
    coordinatorName: "Leila Hassan",
    receiverId: "u-dev",
    receiverName: "Dev Patel",
    campName: "Camp Meera",
    resourceType: "clothing",
    quantity: 40,
    quantityUnit: "blankets",
    declaredAmount: 40,
    stage: "confirmed",
    stageHistory: [
      { stage: "pending", at: hoursAgo(72), by: "Ananya Rao" },
      { stage: "donated", at: hoursAgo(70), by: "Ananya Rao" },
      {
        stage: "received_by_coordinator",
        at: hoursAgo(60),
        by: "Leila Hassan",
      },
      { stage: "in_transit", at: hoursAgo(50), by: "Leila Hassan" },
      { stage: "delivered", at: hoursAgo(36), by: "Dev Patel" },
      { stage: "confirmed", at: hoursAgo(24), by: "Dev Patel" },
    ],
    proofs: [
      {
        id: "pf-1005-a",
        uploadedBy: "donor",
        uploaderName: "Ananya Rao",
        kind: "receipt",
        fileName: "blanket-receipt.jpg",
        dataUrl: "",
        mimeType: "image/jpeg",
        amountEntered: 40,
        uploadedAt: hoursAgo(70),
        verification: "verified",
      },
      {
        id: "pf-1005-d",
        uploadedBy: "receiver",
        uploaderName: "Dev Patel",
        kind: "distribution_record",
        fileName: "ward-list.pdf",
        dataUrl: "",
        mimeType: "application/pdf",
        amountEntered: 40,
        uploadedAt: hoursAgo(24),
        verification: "verified",
      },
    ],
    disputed: false,
    createdAt: hoursAgo(72),
    notes: "Distributed to the elderly ward. Closed.",
  },
];
