/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppFeedRouteImport } from './routes/_app/feed'
import { Route as AppMapRouteImport } from './routes/_app/map'
import { Route as AppPostRouteImport } from './routes/_app/post'
import { Route as AppSurplusRouteImport } from './routes/_app/surplus'
import { Route as AppTransactionsRouteImport } from './routes/_app/transactions'
import { Route as AppFeedIdRouteImport } from './routes/_app/feed.$id'
import { Route as AppTransactionsIdRouteImport } from './routes/_app/transactions.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPostRoute = AppPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSurplusRoute = AppSurplusRouteImport.update({
  id: '/surplus',
  path: '/surplus',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFeedIdRoute = AppFeedIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppFeedRoute,
} as any)
const AppTransactionsIdRoute = AppTransactionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTransactionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AppAuditRoute
  '/dashboard': typeof AppDashboardRoute
  '/feed': typeof AppFeedRouteWithChildren
  '/map': typeof AppMapRoute
  '/post': typeof AppPostRoute
  '/surplus': typeof AppSurplusRoute
  '/transactions': typeof AppTransactionsRouteWithChildren
  '/feed/$id': typeof AppFeedIdRoute
  '/transactions/$id': typeof AppTransactionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AppAuditRoute
  '/dashboard': typeof AppDashboardRoute
  '/feed': typeof AppFeedRouteWithChildren
  '/map': typeof AppMapRoute
  '/post': typeof AppPostRoute
  '/surplus': typeof AppSurplusRoute
  '/transactions': typeof AppTransactionsRouteWithChildren
  '/feed/$id': typeof AppFeedIdRoute
  '/transactions/$id': typeof AppTransactionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/audit': typeof AppAuditRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/feed': typeof AppFeedRouteWithChildren
  '/_app/map': typeof AppMapRoute
  '/_app/post': typeof AppPostRoute
  '/_app/surplus': typeof AppSurplusRoute
  '/_app/transactions': typeof AppTransactionsRouteWithChildren
  '/_app/feed/$id': typeof AppFeedIdRoute
  '/_app/transactions/$id': typeof AppTransactionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/dashboard'
    | '/feed'
    | '/map'
    | '/post'
    | '/surplus'
    | '/transactions'
    | '/feed/$id'
    | '/transactions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/dashboard'
    | '/feed'
    | '/map'
    | '/post'
    | '/surplus'
    | '/transactions'
    | '/feed/$id'
    | '/transactions/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/audit'
    | '/_app/dashboard'
    | '/_app/feed'
    | '/_app/map'
    | '/_app/post'
    | '/_app/surplus'
    | '/_app/transactions'
    | '/_app/feed/$id'
    | '/_app/transactions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/map': {
      id: '/_app/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/post': {
      id: '/_app/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof AppPostRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/surplus': {
      id: '/_app/surplus'
      path: '/surplus'
      fullPath: '/surplus'
      preLoaderRoute: typeof AppSurplusRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/feed/$id': {
      id: '/_app/feed/$id'
      path: '/$id'
      fullPath: '/feed/$id'
      preLoaderRoute: typeof AppFeedIdRouteImport
      parentRoute: typeof AppFeedRoute
    }
    '/_app/transactions/$id': {
      id: '/_app/transactions/$id'
      path: '/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof AppTransactionsIdRouteImport
      parentRoute: typeof AppTransactionsRoute
    }
  }
}

interface AppFeedRouteChildren {
  AppFeedIdRoute: typeof AppFeedIdRoute
}

const AppFeedRouteChildren: AppFeedRouteChildren = {
  AppFeedIdRoute: AppFeedIdRoute,
}

const AppFeedRouteWithChildren =
  AppFeedRoute._addFileChildren(AppFeedRouteChildren)

interface AppTransactionsRouteChildren {
  AppTransactionsIdRoute: typeof AppTransactionsIdRoute
}

const AppTransactionsRouteChildren: AppTransactionsRouteChildren = {
  AppTransactionsIdRoute: AppTransactionsIdRoute,
}

const AppTransactionsRouteWithChildren = AppTransactionsRoute._addFileChildren(
  AppTransactionsRouteChildren,
)

interface AppRouteRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFeedRoute: typeof AppFeedRouteWithChildren
  AppMapRoute: typeof AppMapRoute
  AppPostRoute: typeof AppPostRoute
  AppSurplusRoute: typeof AppSurplusRoute
  AppTransactionsRoute: typeof AppTransactionsRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFeedRoute: AppFeedRouteWithChildren,
  AppMapRoute: AppMapRoute,
  AppPostRoute: AppPostRoute,
  AppSurplusRoute: AppSurplusRoute,
  AppTransactionsRoute: AppTransactionsRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
